FORMAT: 1A
HOST: https://api.thingoncloud.com/

# Public Service API

The purpose of the API is to provide simple way to manage collections of values gathered from remote sensors via Direct service.

Following operations can be performed:
+ managing (create/delete/update) external entry points for sensors
+ controlling access to the entry points
+ sharing values from sensors
+ managing types of values
+ analizing historical values

## Group User

This resource is responsible for providing information about the current user. 

## Users Collection [/users]

Lists users in behalf of which all the further operations can be performed.

The resource must be requested in case when *userUUID* is not known  
as it will be necessary to make any other API calls from now on.

*userUUID* will never change and it can be cached locally.

This resource does not have any attributes. Instead it offers the initial
API affordances in the form of the links in the JSON body.

It is recommend to follow the “url” link values,
[Link](https://tools.ietf.org/html/rfc5988) or Location headers where
applicable to retrieve resources. Instead of constructing your own URLs,
to keep your client decoupled from implementation details.

### List All Users [GET]
+ Response 200 (application/json)
    + Body
        
            {
              "self": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "owner": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "parent": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "user": {
                "self": {
                  "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                  "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
                },
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "email": "name.surname@email.com",
                "password": null,
                "username": "Name",
                "usersurname": "Surname",
                "timezone": "Europe/London",
                "group": null,
                "children": {
                  "applications": {
                    "id": null,
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications"
                  },
                  "directs": {
                    "id": null,
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/directs"
                  },
                  "endpoints": {
                    "id": null,
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/endpoints"
                  },
                  "values": {
                    "id": null,
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/values"
                  }
                }
              }
            }
        
## User Single [/users/{userUUID}]

Retrievs details of the particular user and updates it.

Following fields can be updated:
+ **username**
+ **usersurname**
+ **password**
+ **timezone**

+ Parameters
    + userUUID (required, string, `U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838`) ... The page of questions to return

### User [GET]
+ Response 200 (application/json)
    + Body
    
            {
              "self": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "owner": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "parent": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "user": {
                "self": {
                  "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                  "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
                },
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "email": "name.surname@email.com",
                "password": null,
                "username": "Name",
                "usersurname": "Surname",
                "timezone": "Europe/London",
                "group": null,
                "children": {
                  "applications": {
                    "id": null,
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications"
                  },
                  "directs": {
                    "id": null,
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/directs"
                  },
                  "endpoints": {
                    "id": null,
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/endpoints"
                  },
                  "values": {
                    "id": null,
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/values"
                  }
                }
              }
            }
            
### Update User [POST]

+ Request (application/json)

        {
            "password": "MyNewPassword",
            "username": "NewName",
            "usersurname": "NewSurname",
            "timezone": "Europe/Lisbon",
        }
            
+ Response 200 (application/json)
    + Body
        
            {
              "self": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "owner": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "parent": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "user": {
                "self": {
                  "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                  "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
                },
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "email": "name.surname@email.com",
                "password": null,
                "username": "NewName",
                "usersurname": "NewSurname",
                "timezone": "Europe/Lisbon",
                "group": null,
                "children": {
                  "applications": {
                    "id": null,
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications"
                  },
                  "directs": {
                    "id": null,
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/directs"
                  },
                  "endpoints": {
                    "id": null,
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/endpoints"
                  },
                  "values": {
                    "id": null,
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/values"
                  }
                }
              }
            }

## Group Directs

Direct managment

## Directs Collection [/users/{userUUID}/directs]
+ Parameters
    + userUUID (required, string, `U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838`) ... The page of questions to return

### List All Directs [GET]
+ Response 200 (application/json)
    + Headers

            Link: </questions?page=2>; rel="next"

    + Body
    
            {}
            
### Create a New Direct [POST]
+ Request (applications/json)
    + Body
    
            {
                "name": "thisIsMyApplication_success",
                "authType": "oauth",
                "resources": "/users"
            }

+ Response 200 (application/json)
    + Body
    
            {}
            
## Direct Single [/users/{userUUID}/directs/{directUUID}]
+ Parameters
    + userUUID (required, string, `U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838`) ... The page of questions to return
    + directUUID (required, string, `1`) ... The page of questions to return

### Direct [GET]
+ Response 200 (application/json)
    + Body

            {}

### Update Direct [POST]
+ Request (applications/json)
    + Body
    
            {
                "name": "thisIsMyApplication_success",
                "authType": "oauth",
                "resources": "/users"
            }

+ Response 200 (application/json)
    + Body

            {}

### Delete Direct [DELETE]
+ Response 204

## Group Applications

Applications introduction

## Applications Collection [/users/{userUUID}/applications]
+ Parameters
    + userUUID (required, string, `U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838`) ... The page of questions to return
    
### List All Applications [GET]
+ Response 200 (applications/json)
    + Body
        
            {
              "self": {
                "id": null,
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications"
              },
              "owner": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "parent": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "applications": [
                {
                  "self": {
                    "id": "P-0ba20202-051b-4c14-8806-f65da33b9f1e-98346",
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications/P-0ba20202-051b-4c14-8806-f65da33b9f1e-98346"
                  },
                  "id": "P-0ba20202-051b-4c14-8806-f65da33b9f1e-98346",
                  "name": "myDirect4ReadApp",
                  "authType": "basic",
                  "resources": "/direct",
                  "internal": false,
                  "userKey": "EMVuRWxA50SmbuVwtw0heq7bbsndfLXnIxOnVKpq_myDirect4ReadApp",
                  "userSecret": null,
                  "used": null,
                  "created": "2015-04-06T11:49:17.634+01:00",
                  "lastUsed": null,
                  "updated": null
                },
                {
                  "self": {
                    "id": "P-39420e02-b128-4e7e-858f-766f3ccc4972-74395",
                    "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications/P-39420e02-b128-4e7e-858f-766f3ccc4972-74395"
                  },
                  "id": "P-39420e02-b128-4e7e-858f-766f3ccc4972-74395",
                  "name": "myDirect3ReadApp",
                  "authType": "oauth",
                  "resources": "/direct",
                  "internal": false,
                  "userKey": "enzmgdqItrKncOlOYjXxRKTDE0syF9idsItPWrK2_myDirect3ReadApp",
                  "userSecret": null,
                  "used": null,
                  "created": "2015-04-06T11:49:17.631+01:00",
                  "lastUsed": null,
                  "updated": null
                }
              ]
            }

### Create a New Application [POST]
+ Request (applications/json)
    + Body
    
            {
                "name": "thisIsMyApplication_success",
                "authType": "oauth",
                "resources": "/users"
            }

+ Response 200 (applications/json)
    + Headers

            Location: http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications/P-12882ebd-0441-4213-b77a-d3130f33541f-59183

    + Body
        
            {
              "self": {
                "id": "P-12882ebd-0441-4213-b77a-d3130f33541f-59183",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications/P-12882ebd-0441-4213-b77a-d3130f33541f-59183"
              },
              "owner": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "parent": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "application": {
                "self": {
                  "id": "P-12882ebd-0441-4213-b77a-d3130f33541f-59183",
                  "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications/P-12882ebd-0441-4213-b77a-d3130f33541f-59183"
                },
                "id": "P-12882ebd-0441-4213-b77a-d3130f33541f-59183",
                "name": "thisIsMyApplication_success",
                "authType": "oauth",
                "resources": "/users",
                "internal": false,
                "userKey": "H4u2RUI94JYH2OzSHYedmXHmnEJ4DfqYjnn1XKKg_thisIsMyApplication_success",
                "userSecret": "Lpb9m5XVhBWAklpvxRv2dhsaOkvpYPn4QGerighvVty8X4L1GNv7fSl5MhMe3XdaCs3C8BGSD7K5806KITIBYPHWWK",
                "used": null,
                "created": "2015-04-18T08:12:58.264+01:00",
                "lastUsed": null,
                "updated": null
              }
            }
            
## Application Single [/users/{userUUID}/applications/{applicationUUID}]
+ Parameters
    + userUUID (required, string, `U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838`) ... The page of questions to return
    + applicationUUID (required, string, `P-0182b795-171a-41eb-938f-05255be321c8-71385`) ... The page of questions to return
    
### Application [GET]
+ Response 200 (applications/json)
    + Body
    
            {
              "self": {
                "id": "P-0182b795-171a-41eb-938f-05255be321c8-71385",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications/P-0182b795-171a-41eb-938f-05255be321c8-71385"
              },
              "owner": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "parent": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "application": {
                "self": {
                  "id": "P-0182b795-171a-41eb-938f-05255be321c8-71385",
                  "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications/P-0182b795-171a-41eb-938f-05255be321c8-71385"
                },
                "id": "P-0182b795-171a-41eb-938f-05255be321c8-71385",
                "name": "thisIsMyApplication_success",
                "authType": "oauth",
                "resources": "/users",
                "internal": false,
                "userKey": "eqa8azmnV4UCVYDMAzq9SXw6ORw7bhZsnRYA28gb_thisIsMyApplication_success",
                "userSecret": null,
                "used": null,
                "created": "2015-04-18T07:52:21.107+01:00",
                "lastUsed": null,
                "updated": null
              }
            }
            
### Update Application [POST]
+ Request (application/json)
    + Body
    
            {
              "name": "DwpD3GTiDpguCun9jTNEW",
              "authType": "basic",
              "resources": "/users,/ping"
            }
            
+ Response 200 (applications/json)
    + Body
    
            {
              "self": {
                "id": "P-620e55aa-c533-4dd0-b75f-056fbe2f014b-75323",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications/P-620e55aa-c533-4dd0-b75f-056fbe2f014b-75323"
              },
              "owner": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "parent": {
                "id": "U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838",
                "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838"
              },
              "application": {
                "self": {
                  "id": "P-620e55aa-c533-4dd0-b75f-056fbe2f014b-75323",
                  "href": "http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications/P-620e55aa-c533-4dd0-b75f-056fbe2f014b-75323"
                },
                "id": "P-620e55aa-c533-4dd0-b75f-056fbe2f014b-75323",
                "name": "DwpD3GTiDpguCun9jTNEW",
                "authType": "basic",
                "resources": "/users,/ping",
                "internal": false,
                "userKey": "5iVdN5ACDFG1Eqldt178Nsw7dr789IhT5OWregve_DwpD3GTiDpguCun9jT",
                "userSecret": null,
                "used": null,
                "created": "2015-04-18T06:59:35.954+01:00",
                "lastUsed": null,
                "updated": "2015-04-18T06:59:36.157+01:00"
              }
            }
            
### Delete Application [DELETE]
+ Response 204
            
## Group Endpoints

Endpoints description

## Endpoints Collection [/users/{userUUID}/endpoints]
+ Parameters
    + userUUID (required, string, `U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838`) ... The page of questions to return

### List All Endpoints [GET]
+ Response 200 (applications/json)
    + Body
        
            {}

### Create a New Endpoint [POST]
+ Request (applications/json)
    + Body
    
            {

            }

+ Response 200 (applications/json)
    + Headers

            Location: http://localhost:8189/api/v1/users/U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838/applications/P-12882ebd-0441-4213-b77a-d3130f33541f-59183

    + Body
        
            {}

## Endpoint Single [/users/{userUUID}/endpoints/{endpointUUID}]
+ Parameters
    + userUUID (required, string, `U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838`) ... The page of questions to return
    + endpointUUID (required, string, `1`) ... The page of questions to return

### Endpoint [GET]
+ Response 200 (applications/json)
    + Body
        
            {}

### Update Endpoint [POST]
+ Request (applications/json)
    + Body
    
            {
                "name": "thisIsMyApplication_success",
                "authType": "oauth",
                "resources": "/users"
            }

+ Response 200 (applications/json)
    + Body
        
            {}

### Delete Endpoint [DELETE]
+ Response 204

## Group Values

Values description

## Sources Collection [/users/{userUUID}/values/{serviceId}]
+ Parameters
    + userUUID (required, string, `U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838`) ... The page of questions to return
    + serviceId (required, string, `1`) ... The page of questions to return

### List All Sources [GET]
+ Response 200 (applications/json)
    + Body
        
            {}

## Source Single [/users/{userUUID}/values/{serviceId}/{sourceId}]
+ Parameters
    + userUUID (required, string, `U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838`) ... The page of questions to return
    + serviceId (required, string, `1`) ... The page of questions to return
    + sourceId (required, string, `1`) ... The page of questions to return
    
### Source [GET]
+ Response 200 (applications/json)
    + Body
        
            {}

### Delete Source [DELETE]
+ Response 204

## Slot [/users/{userUUID}/values/{serviceId}/{sourceId}/{slotNo}]
+ Parameters
    + userUUID (required, string, `U-f8053d8e-68b7-4a75-a218-83efd09cdca7-35838`) ... The page of questions to return
    + serviceId (required, string, `1`) ... The page of questions to return
    + sourceId (required, string, `1`) ... The page of questions to return
    + slotNo (required, string, `1`) ... The page of questions to return
    
### Delete Slot [DELETE]
+ Response 204 
